### ISSUE TITLE
Reachability check doesn't work in iOS simulator when toggling WiFi

### ISSUE THREAD

**Issue by tenjinsoftware** [tonymillion/Reachability#101]
When I run my iOS 7/8 app in the simulator and toggle WiFi OFF on my Mac I get the "unreachable" status. That works fine.

However, when I toggle WiFi back ON I get a Notification (or call to Block) with the same "unreachable" status.

Is this an issue with the simulator only, or a more general issue, and is there a workaround?

FYI, I'm running Xcode 6 on Yosemite.

Thanks

Darren.

**Comment by tenjinsoftware** [comment]
Hi,

I see that the ticket has been closed without comments.

Is this covered in the doc somewhere? I have looked but I can't see anything.

Thanks

Darren.

**Comment by tonymillion** [comment]
https://github.com/tonymillion/Reachability/blob/master/README.md#reachability

Its a well known issue (indeed there are several closed tickets r.e. this issue)
