### ISSUE TITLE
Duplicate Reachability class definition warning on iOS 9 Beta2

### ISSUE THREAD

**Issue by leosobral** [tonymillion/Reachability#107]
hi,

when running my app on iOS9 Beta2, I get the following warning on startup: "
objc[447]: Class Reachability is implemented in both /System/Library/PrivateFrameworks/Notes.framework/Notes and /var/mobile/Containers/Bundle/Application/DC54FB75-EC57-4882-80F6-98F09560402F/FOO.app/FOO. One of the two will be used. Which one is undefined."

we include Reachability through cocoapods, by using: pod 'Reachability', :head

simplest fix is to rename the Reachability class to avoid clash with the built-in one on iOS 9. I tested that renaming fixes the warning.

ps: we dont use the use_frameworks! flag, mentioned in other issues.

other suggestions?

**Comment by Hackmodford** [comment]
I found the same issue.

**Comment by emauro** [comment]
I saw it using XCode Beta 4. I upgrade to Beta 6 and I haven't see the message anymore.

**Comment by leosobral** [comment]
fixed on later beta release.
