### ISSUE TITLE
tvos support

### ISSUE THREAD

**Issue by tbaranes** [tonymillion/Reachability#113]
Do you think to update your pod to support this new platform soon? Or a branch to avoid breaking the master until CocoaPods release a version working with tvos? 

I don't think you will have any issue to handle it with the current version.

**Comment by kleinlieu** [comment]
@gabek can you tag a new version and upload a new version to Cocoapods? If you give me write access tot he project and the Cocoapods spec I can do it too

**Comment by kleinlieu** [comment]
Also @tonymillion could you make a new release on CocoaPods? If not I can help if I can get write access!

**Comment by gabek** [comment]
@kleinlieu: Sorry, I don't have access to do that.  It's all Tony!

**Comment by gabek** [comment]
@tonymillion: Could you help getting this released?
