### ISSUE TITLE
Http status code

### ISSUE THREAD

**Issue by wgywgy** [tonymillion/Reachability#129]
When server return Http status code 500 or other, Does the Lib return Not reachable?

**Comment by christocracy** [comment]
I'm just a user of this lib but I doubt that would be the case.  If the server is "reachable" enough to return an HTTP response, then the server is clearly "reachable".

If I phone someone and dial a wrong number, the person on the other end says "I'm sorry, you've dialed the wrong number".  If the called failed to complete, *then* the network is "unreachable".
