### ISSUE TITLE
Enum previously declared

### ISSUE THREAD

**Issue by Meekohi** [tonymillion/Reachability#135]
I get the error `Enumeration previously declared with nonfixed underlying type` when trying to compile with this related to `typedef NS_ENUM(NSInteger, NetworkStatus) {`

Is there some better way to handle this when NetworkStatus is already defined?

**Comment by Meekohi** [comment]
Nevermind, managed to rename the other library's use without too much effort.

**Comment by jefby** [comment]
Thanks
