### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by premedios** [tonymillion/Reachability#180]
I'm getting the message: 

dyld: Symbol not found: _OBJC_CLASS_$_Reachability
  Referenced from: /Users/pedro/Library/Developer/CoreSimulator/Devices/119DB089-4C85-4E74-909C-7FBB4E13ECD2/data/Containers/Bundle/Application/A0BAE4C3-4425-4B70-B54C-7D7F7E0D269A/DriveTest.app/Frameworks/FLOTelematicsSDK.framework/FLOTelematicsSDK
  Expected in: flat namespace
 in /Users/pedro/Library/Developer/CoreSimulator/Devices/119DB089-4C85-4E74-909C-7FBB4E13ECD2/data/Containers/Bundle/Application/A0BAE4C3-4425-4B70-B54C-7D7F7E0D269A/DriveTest.app/Frameworks/FLOTelematicsSDK.framework/FLOTelematicsSDK

I have added the Reachbility.m and Reachability.h files to the project.

The Xcode project is Objective-C (Cordova) and Using Reachability 3.2

The FLOTelematicsSDK is embedded and I added SystemConfiguration.framework and it still doesn't see the Reachability class!!!

**Comment by georgenimber** [comment]
Any updates on this?

**Comment by premedios** [comment]
I solved the issue. I used CocoaPods to load FLOTelematicsSDK Standard edition and Reachability and it worked.
