### ISSUE TITLE
Privacy manifest required by Apple

### ISSUE THREAD

**Issue by wenfeng-duan** [tonymillion/Reachability#192]
Hi team,

Starting with Spring 2024 Apple requires third-party SDKs to add a Privacy Manifest file. 
Apple has explicitly mentioned Reachability as one of the third party SDKs that must include a privacy manifest otherwise any App that includes it is not allowed to release an update (or new app) to the store.

Is there any plans to add a privacy manifest? 

https://developer.apple.com/support/third-party-SDK-requirements/
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Thanks,
Duan

**Comment by lamdaniel** [comment]
@tonymillion

**Comment by RideShi** [comment]
+1

**Comment by krishnaprasadkuchur** [comment]
+1

**Comment by RayGTile** [comment]
I don't see why Apple thinks this needs privacy manifests.  I think it might be in error (or they are talking about some other Reachability package).  Other than 3rd party tracking (which this package does not do), these would be APIs that would require one:  https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

However, Reachability is using *none* of the ones in that document.

I'm not a contributor here; I'm an interested party, making sure all of my stuff is ready for privacy manifests as well.

**Comment by RayGTile** [comment]
Actually, 3.7.5 does have a manifest included.  :D

**Comment by TrinhNTLine** [comment]
I use CocoaPods to add Reachability to the project. But it seems that the latest version does not include the Privacy Manifest file. 
Do we need to update the podspec file?

**Comment by RayGTile** [comment]
I pulled it in using Swift Package Manager.

**Comment by zcsyIos** [comment]
When I updated to the latest version using cacaopod, I found that the file was not available，(PrivacyInfo.xcprivacy)，we are object-C product please check quickly。oh fuck

**Comment by zcsyIos** [comment]
pod 'Reachability', :git => 'https://github.com/tonymillion/Reachability.git'

Using this method to execute pod, pull the latest code from the master branch without specifying a version, the author fixed the patch on the master

**Comment by zcsyIos** [comment]
If you have any questions about the PrivacyInfo.xcprivacy, please refer to here ：https://www.jianshu.com/p/9a9ec34395e2

**Comment by krishnaprasadkuchur** [comment]
Would greatly appreciate if we could create a tag for the  current `master` branch with changes made to support both SPM and Cocoapods @tonymillion

**Comment by TeeNT1** [comment]
> Would greatly appreciate if we could create a tag for the current `master` branch with changes made to support both SPM and Cocoapods @tonymillion

+1

**Comment by TeeNT1** [comment]
My app is about to be released. I hope you will soon create a tag for the latest code on the master branch @tonymillion

**Comment by tonymillion** [comment]
Should be fixed now new pod file has been pushed
