### ISSUE TITLE
Need login for internet

### ISSUE THREAD

**Issue by hashier** [tonymillion/Reachability#39]
In my network I need to authenticate before having 'real' access to the internet. Before that authentication I can resolve DNS hostnames to IP but not more.

Reachability always tells me that I am connected as long as I get an DNS reply. There should be an option to check e.g. with a ping request or maybe even do a HEAD http request to see if we have 'real' internet.

**Comment by tonymillion** [comment]
I can't really do anything about captive portals like this.

The best bet would be to do this at the application level i.e. 
 1. Create a server endpoint that returns a specific response e.g. `OK_APPNAME`
 2. When reachability reports its reachable attempt to contact a server you control over HTTP and check the response.
 3. if response != `OK_APPNAME` then its a safe bet to say you have some kind of MITM

**Comment by hashier** [comment]
It would be cool if reachability would help out with this for example set an endpoint `www.example.com/json` and when this json returns something predefined reachability says "internet available".

Or trying to fetch the header from google.com and see if it says google in it or something else, e.g. airport/hotel name of providing internet service.
