### ISSUE TITLE
SCNetworkReachabilitySetDispatchQueue() failed: Permission denied

### ISSUE THREAD

**Issue by vividcode** [tonymillion/Reachability#44]
I am getting this error upon calling [Reachability startNotifier] function.

Here is my code snippet: 

```
Reachability *r = [Reachability reachabilityWithHostname:host];    
r.reachableBlock = ^(Reachability*reach)
{
    // Update the UI on the main thread

    });
};    
r.unreachableBlock = ^(Reachability*reach)
{
    // Update the UI on the main thread with error alert

    });
};    
[r startNotifier];    
```

I can very well browse the host from Safari. What maybe the issue?
None of the success/failure blocks above get called.

**Comment by sunny131984** [comment]
HI Guyz,
I try to use reachability latest version and my net module works fine but i need my application is updates if network loss or network resume. i try to set callback event but it not working properly.
