### ISSUE TITLE
Unable to use IP addresses?

### ISSUE THREAD

**Issue by beloso** [tonymillion/Reachability#6]
I am trying to use your class to check my reachability to a local IP address like so:

```
hostReach = [Reachability reachabilityWithHostname:@"192.168.2.113"];
```

But this never gets to execute my reachable and unreachable blocks. The same goes for internet connection:

```
internetReach = [Reachability reachabilityForInternetConnection];
```

It will not execute my reachable or unreachable blocks. And I know for certain that I have reachability to both those hosts.

I am running on the simulator.

**Comment by zykis** [comment]
A callback is issued when there is a CHANGE in the reachability. For names, the change occurs once the name has been resolved. For addresses, the reachability flags are already known so there's no change to report. In short, for addresses, follow your call to SCNetworkReachabilitySCheduleWithRunLoop() with a call to SCNetworkReachabilityGetFlags(). That will give you the current reachability status and you'll get a notification should that status ever change. For names, you "can" call SCNetworkReachabilityGetFlags () after scheduling and then, after the name resolution process has completed, you'll get a callback.
   - Allan

That's the official answer for subject. But I still can't get it.
