### ISSUE TITLE
reachabilitySerialQueue assignment type

### ISSUE THREAD

**Issue by bassrock** [tonymillion/Reachability#82]
I am using swift and when building reachability using the cocoa pods swift branch, I get an error on line 44 of the main:

``` obj-c
@property (nonatomic, strong) dispatch_queue_t          reachabilitySerialQueue;
```

to fix the error i change it to:

``` obj-c
@property (nonatomic, assign) dispatch_queue_t          reachabilitySerialQueue;
```

**Comment by katzlbt** [comment]
I cloned the git just now on the commandline and get the compile error:

...SuperSolitaire/Classes/Reachability.m:44:1: Property with 'retain (or strong)' attribute must be of object type 
(dispatch_queue_t is not an NSObject and can not receive retain messages)

@property (nonatomic, strong) dispatch_queue_t          reachabilitySerialQueue;

**Comment by klattimer** [comment]
Surely this line should be 

@property (nonatomic) dispatch_queue_t reachabilitySerialQueue;

**Comment by tonymillion** [comment]
No it should be `strong`, its valid for all versions above iOS6

we don't support iOS5 (if you read the docs they tell you to use an older tag that still supports iOS5). for reference `dispatch_queue_t` became a retainable object as of iOS6

**Comment by klattimer** [comment]
ah, spotted.
