### ISSUE TITLE
reachabilitySerialQueue is assign not strong type

### ISSUE THREAD

**Issue by sjeast** [tonymillion/Reachability#86]
I'm using Reachability as a CocoaPod which is installing V3.2 which I think is the latest version.
When compiling I get a warning on this line
@property (nonatomic, assign) dispatch_queue_t          reachabilitySerialQueue;
of
Assigning retained object to unsafe property

And the code then crashes when run. When I change the assign to strong the problem goes away and it all works.

**Comment by tonymillion** [comment]
The current head is 

`@property (nonatomic, strong) dispatch_queue_t          reachabilitySerialQueue;`

Check you are getting the correct version

**Comment by sjeast** [comment]
OK will check this out - perhaps CocoaPods is fetching the wrong version - it says it is getting 3.2 but clearly it isn't. Will dig further.

**Comment by sjeast** [comment]
OK so something very odd must have been happening with CocoaPods last week - cleaned the whole pod structrure and did a pod install and it all worked fine again.
