### ISSUE TITLE
App fails to build after adding this Reachability class

### ISSUE THREAD

**Issue by segadude** [tonymillion/Reachability#90]
I wanted to convert my app to ARC, so I replaced the Apple Reachability class with this one. But now my app won't compile. I get the following error: "Semantic Issue: Property with 'retain (or strong)' attribute must be of object type". The error occurs at line 44 of Reachability.m. I am using Xcode 6.1 with the iOS 8.1 SDK. The app has a deployment target of 4.3. I was able to compile and run the iOS sample project no problem so I don't know why my project won't compile.

**Comment by steffenfrost** [comment]
Did you remove the  -fno-objc-arc compiler flags in Build Phases/Compile Sources for the Reachability classes?

**Comment by segadude** [comment]
None of the files have compiler flags. I tried removing the Reachability class files, then converting the project to ARC, which I did successfully, but I still get the same error.
