### ISSUE TITLE
Facing issue on WIFI when host is not Reachable 

### ISSUE THREAD

**Issue by sunny131984** [tonymillion/Reachability#91]
I have download code and test it for my requirement. It gives proper callback when my wifi is on/Off.
In my case i am connected Via WIFI and if Wifi Lan cabel is unplugged at that time my device is connected with wifi but wifi don't have internet connectivity . In this test case i need prompt when my host is not reachable. i have mention my test case below.

1 ) Run your Application and your device must connected with only WIFI no cellular data.
2 ) your application is in foreground.
3 ) Unplugged your Lan cabel from the Router.

I want to notify here once you router don't have internet connection. I have tested this code it always gives RechableviaWifi. is there any way to detect that you don't have internet connection over Wifi.

**Comment by tonymillion** [comment]
This is something you'll have to do yourself as it requires a request to be made to a known endpoint to make sure you actually get a valid response back - its beyond the scope of reachability.
