### ISSUE TITLE
iOS Deployment Target 5.0   ERROR！How Can I Fix it?

### ISSUE THREAD

**Issue by soulin** [tonymillion/Reachability#93]
@property (nonatomic, strong) dispatch_queue_t          reachabilitySerialQueue;
-----------
property with 'retain (or strong)' attribute must be of object type
========

How Can I Fix it?

**Comment by tonymillion** [comment]
The simplest thing would be not to compile for iOS5 - its not supported any more. If you are using HEAD then the minimum spec is now iOS6 try one of the older tags or change the `strong` to `assign` but you will have to retain the dispatch queue yourself
